from typing import Protocol, List, Optional
from domain.lost_items.models.lost_item import LostItem

class LostItemRepositoryPort(Protocol):
    def find_by_id(self, item_id: str) -> Optional[LostItem]: ...
    def save(self, item: LostItem) -> LostItem: ...
    def update(self, item: LostItem) -> LostItem: ...
    def find_removed(self, limit: int = 100) -> List[LostItem]: ...
